# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

@fibStore = {}

def fib(x)
  if x == 1 || x == 2
    return 1
  elsif @fibStore.keys.include? x
    return @fibStore[x]
  else
    a = @fibStore[x-1] = fib(x-1)
    b = @fibStore[x-2] = fib(x-2)
    return a + b
  end
end

i = 1
sum = 0
while fib(i) < 4000000 do
  sum += fib(i) if fib(i) % 2 == 0
  i = i + 1
end

puts sum